name: fox
description: "A simple, local-first notes application."

publish_to: 'none'
version: 1.3.0+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/launchscreen/

flutter_native_splash:
  android_12: 
    image: assets/images/launchscreen/logo.png
    branding: assets/images/launchscreen/branding.png
  color: "#1A1A1A"
  android: true
  ios: true
  # flutter pub run flutter_native_splash:create

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#228B22"
  adaptive_icon_foreground: "assets/images/icon/icon.png"
  # flutter pub run flutter_launcher_icons:main
